[color-theme]
name = 'Cobalt'

[color-theme.base]
black = '#122738'
blue = '#0088ff'
current-background = '#1F4662'
cyan = '#9EFFFF'
dim-text = '#aaaaaa'
green = '#A5FF90'
grey = '#3B5364'
magenta = '#FB94FF'
orange = '#FF9D00'
primary-background = '#193549'
purple = '#FF68B8'
red = '#FF628C'
secondary-background = '#15232D'
text = '#FFFFFF'
white = '#E1EFFF'
yellow = '#FFC600'

[color-theme.syntax]
attribute = '$yellow'
"bracket.color.1" = '#FFA500'
"bracket.color.2" = '#FF69B4'
"bracket.color.3" = '#00FF7F'
"bracket.unpaired" = '$red'
builtinType = '$purple'
comment = '$blue'
constant = '$red'
constructor = '$yellow'
embedded = '$cyan'
enum = '$purple'
enum-member = '$cyan'
enumMember = '$cyan'
escape = '$orange'
field = '$cyan'
function = '$yellow'
"function.method" = '$yellow'
interface = '$purple'
keyword = '$orange'
"markup.bold" = '$cyan'
"markup.heading" = '$yellow'
"markup.italic" = '$cyan'
"markup.link.label" = '$green'
"markup.link.text" = '$green'
"markup.link.url" = '$cyan'
"markup.list" = '$yellow'
method = '$yellow'
number = '$red'
property = '$cyan'
"punctuation.delimiter" = '$white'
selfKeyword = '$cyan'
string = '$green'
"string.escape" = '$orange'
struct = '$purple'
structure = '$purple'
tag = '$cyan'
"text.reference" = '$green'
"text.title" = '$yellow'
"text.uri" = '$cyan'
type = '$purple'
"type.builtin" = '$purple'
typeAlias = '$purple'
variable = '$white'
"variable.other.member" = '$cyan'

[color-theme.ui]
"activity.background" = '#122738'
"activity.current" = '$primary-background'
"completion.background" = '$secondary-background'
"completion.current" = '$primary-background'
"completion_lens.foreground" = '$dim-text'
"debug.breakpoint" = '#FF5630'
"debug.breakpoint.hover" = '#FF563066'
"editor.background" = '$primary-background'
"editor.caret" = '$yellow'
"editor.current_line" = '$current-background'
"editor.debug_break_line" = '#1F4662'
"editor.dim" = '$dim-text'
"editor.drag_drop_background" = '#12273899'
"editor.drag_drop_tab_background" = '#12273855'
"editor.focus" = '$yellow'
"editor.foreground" = '$text'
"editor.indent_guide" = '$grey'
"editor.link" = '$blue'
"editor.selection" = '#0050A4'
"editor.sticky_header_background" = '#122738'
"editor.visible_whitespace" = '#ffffff52'
"error_lens.error.background" = '#A2292920'
"error_lens.error.foreground" = '#A22929'
"error_lens.other.background" = '#ffffff10'
"error_lens.other.foreground" = '$dim-text'
"error_lens.warning.background" = '#ffc60020'
"error_lens.warning.foreground" = '$yellow'
"hover.background" = '$secondary-background'
"inlay_hint.background" = '#0000001a'
"inlay_hint.foreground" = '$purple'
"lapce.border" = '#0D3A58'
"lapce.button.primary.background" = '$blue'
"lapce.button.primary.foreground" = '$text'
"lapce.dropdown_shadow" = '#00000026'
"lapce.error" = '#A22929'
"lapce.icon.active" = '$text'
"lapce.icon.inactive" = '$dim-text'
"lapce.plugin.author" = '#B0B0B0'
"lapce.plugin.description" = '$dim-text'
"lapce.plugin.name" = '$text'
"lapce.remote.connected" = '#3ad900'
"lapce.remote.connecting" = '$orange'
"lapce.remote.disconnected" = '$red'
"lapce.remote.icon" = '$black'
"lapce.remote.local" = '$blue'
"lapce.scroll_bar" = '#406179cc'
"lapce.tab.active.background" = '$primary-background'
"lapce.tab.active.foreground" = '$text'
"lapce.tab.active.underline" = '$yellow'
"lapce.tab.inactive.background" = '#122738'
"lapce.tab.inactive.foreground" = '$dim-text'
"lapce.tab.inactive.underline" = '#15232D'
"lapce.tab.separator" = '#122738'
"lapce.warn" = '$yellow'
"markdown.blockquote" = '#193549'
"palette.background" = '$secondary-background'
"palette.current.background" = '$primary-background'
"palette.current.foreground" = '$text'
"palette.foreground" = '$dim-text'
"panel.background" = '#122738'
"panel.current.background" = '$current-background'
"panel.current.foreground" = '$text'
"panel.current.foreground.dim" = '$dim-text'
"panel.foreground" = '$dim-text'
"panel.foreground.dim" = '$dim-text'
"panel.hovered.active.background" = '$grey'
"panel.hovered.background" = '#193549'
"panel.hovered.foreground" = '$text'
"panel.hovered.foreground.dim" = '$dim-text'
"source_control.added" = '#3ad900cc'
"source_control.modified" = '#ffc600cc'
"source_control.removed" = '#ff628ccc'
"status.background" = '$secondary-background'
"status.foreground" = '$dim-text'
"status.modal.insert.background" = '$red'
"status.modal.insert.foreground" = '#000000'
"status.modal.normal.background" = '$blue'
"status.modal.normal.foreground" = '#000000'
"status.modal.terminal.background" = '$magenta'
"status.modal.terminal.foreground" = '#000000'
"status.modal.visual.background" = '$yellow'
"status.modal.visual.foreground" = '#000000'
"terminal.background" = '#122738'
"terminal.black" = '#000000'
"terminal.blue" = '#0088ff'
"terminal.bright_black" = '#0050A4'
"terminal.bright_blue" = '#0088ff'
"terminal.bright_cyan" = '#80fcff'
"terminal.bright_green" = '#3ad900'
"terminal.bright_magenta" = '#fb94ff'
"terminal.bright_red" = '#ff628c'
"terminal.bright_white" = '#ffffff'
"terminal.bright_yellow" = '#ffc600'
"terminal.cursor" = '$yellow'
"terminal.cyan" = '#80fcff'
"terminal.foreground" = '#ffffff'
"terminal.green" = '#3ad900'
"terminal.magenta" = '#fb94ff'
"terminal.red" = '#ff628c'
"terminal.white" = '#ffffff'
"terminal.yellow" = '#ffc600'
"tooltip.background" = '$secondary-background'
"tooltip.foreground" = '$text'

[ui]
drop-shadow-width = 0
font-family = ''
font-size = 13
header-height = 35
hover-font-family = ''
hover-font-size = 0
icon-size = 0
list-line-height = 25
open-editors-visible = true
palette-width = 500
scale = 1.0
scroll-width = 10
status-height = 25
tab-close-button = 'Right'
tab-min-width = 100
tab-separator-height = 'Content'
trim-search-results-whitespace = true
