name = "cobalt2"
display-name = "Cobalt2"
description = "The legendary blue and yellow dark theme."
version = "0.1.1"
author = "Patryk Mroczyński"
icon = "logo.png"
repository = "https://github.com/mroczynskip/cobalt2-lapce"
color-themes = ["cobalt2.toml"]
